import "./globals.css";
import MapProvider from './context/MapContext';
import { Toaster } from "@/components/ui/toaster"
import { SessionProvider } from "next-auth/react";
import Providers from "@/components/layouts/Providers";

export const metadata = {
  title: "Geodatavault",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
